# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-06 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='类型名称')),
                ('picture', models.ImageField(null=True, upload_to='static/upload/goodstype', verbose_name='商品类型图片')),
                ('desc', models.TextField(verbose_name='商品类型描述')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
                'db_table': 'GoodsType',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='激活'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uemail',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uphone',
            field=models.CharField(max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upwd',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
    ]
