# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-07 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='购买数量')),
                ('goods', models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.CASCADE, to='index.Goods', verbose_name='商品名称')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '购物车',
                'db_table': 'cartinfo',
                'verbose_name': '购物车',
            },
        ),
    ]
